"""create initial schema

Revision ID: 57944397886c
Revises:
Create Date: 2026-07-29 22:10:21.254058
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "57944397886c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_providers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "internal",
                "external",
                name="provider_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("driver", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column(
            "request_timeout_ms", sa.Integer(), server_default=sa.text("2000"), nullable=False
        ),
        sa.Column(
            "supports_availability", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("supports_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "supports_confirm", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "supports_release", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind != 'external' OR base_url IS NOT NULL",
            name=op.f("ck_inventory_providers_external_provider_requires_base_url"),
        ),
        sa.CheckConstraint(
            "request_timeout_ms > 0", name=op.f("ck_inventory_providers_positive_request_timeout")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_providers")),
        sa.UniqueConstraint("name", name=op.f("uq_inventory_providers_name")),
    )
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_products_name_not_empty")),
        sa.CheckConstraint("length(sku) > 0", name=op.f("ck_products_sku_not_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_table(
        "reservations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "reserving",
                "active",
                "confirming",
                "confirmed",
                "releasing",
                "cancelled",
                "expired",
                "failed",
                name="reservation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(idempotency_key) > 0", name=op.f("ck_reservations_idempotency_key_not_empty")
        ),
        sa.CheckConstraint(
            "length(request_fingerprint) = 64",
            name=op.f("ck_reservations_request_fingerprint_sha256"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_reservations_positive_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_reservations_user_id_idempotency_key")
        ),
    )
    op.create_index(
        "ix_reservations_expiry_worker", "reservations", ["status", "expires_at"], unique=False
    )
    op.create_index(
        "ix_reservations_user_created", "reservations", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "inventory_levels",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "allocation_priority", sa.Integer(), server_default=sa.text("100"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allocation_priority >= 0",
            name=op.f("ck_inventory_levels_non_negative_allocation_priority"),
        ),
        sa.CheckConstraint("on_hand >= 0", name=op.f("ck_inventory_levels_non_negative_on_hand")),
        sa.CheckConstraint(
            "reserved <= on_hand", name=op.f("ck_inventory_levels_reserved_not_above_on_hand")
        ),
        sa.CheckConstraint("reserved >= 0", name=op.f("ck_inventory_levels_non_negative_reserved")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_inventory_levels_positive_version")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_levels_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["inventory_providers.id"],
            name=op.f("fk_inventory_levels_provider_id_inventory_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_levels")),
        sa.UniqueConstraint(
            "product_id", "provider_id", name=op.f("uq_inventory_levels_product_id_provider_id")
        ),
    )
    op.create_index(
        "ix_inventory_levels_product_priority",
        "inventory_levels",
        ["product_id", "allocation_priority"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_orders_reservation_id_reservations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("reservation_id", name=op.f("uq_orders_reservation_id")),
    )
    op.create_table(
        "provider_credentials",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column(
            "auth_type",
            sa.Enum(
                "none",
                "api_key",
                "bearer",
                "basic",
                "oauth2",
                name="provider_auth_type",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'none'"),
            nullable=False,
        ),
        sa.Column("secret_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "public_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "auth_type = 'none' OR secret_ref IS NOT NULL",
            name=op.f("ck_provider_credentials_authenticated_provider_requires_secret_ref"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["inventory_providers.id"],
            name=op.f("fk_provider_credentials_provider_id_inventory_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_credentials")),
        sa.UniqueConstraint("provider_id", name=op.f("uq_provider_credentials_provider_id")),
    )
    op.create_table(
        "reservation_items",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("requested_quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requested_quantity > 0", name=op.f("ck_reservation_items_positive_requested_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_reservation_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_items_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_items")),
        sa.UniqueConstraint(
            "reservation_id",
            "product_id",
            name=op.f("uq_reservation_items_reservation_id_product_id"),
        ),
    )
    op.create_table(
        "inventory_allocations",
        sa.Column("reservation_item_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "held",
                "confirming",
                "confirmed",
                "releasing",
                "released",
                "failed",
                "unknown",
                name="allocation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("hold_idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("provider_hold_reference", sa.String(length=255), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_inventory_allocations_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["inventory_providers.id"],
            name=op.f("fk_inventory_allocations_provider_id_inventory_providers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_item_id"],
            ["reservation_items.id"],
            name=op.f("fk_inventory_allocations_reservation_item_id_reservation_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_allocations")),
        sa.UniqueConstraint(
            "hold_idempotency_key", name=op.f("uq_inventory_allocations_hold_idempotency_key")
        ),
        sa.UniqueConstraint(
            "reservation_item_id",
            "provider_id",
            name=op.f("uq_inventory_allocations_reservation_item_id_provider_id"),
        ),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint(
            "order_id", "product_id", name=op.f("uq_order_items_order_id_product_id")
        ),
    )
    op.create_table(
        "provider_operations",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "check",
                "hold",
                "confirm",
                "release",
                name="provider_operation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "succeeded",
                "failed",
                "unknown",
                name="provider_operation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_provider_operations_non_negative_attempt_count")
        ),
        sa.CheckConstraint(
            "http_status IS NULL OR http_status BETWEEN 100 AND 599",
            name=op.f("ck_provider_operations_valid_http_status"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name=op.f("ck_provider_operations_non_negative_latency"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["inventory_allocations.id"],
            name=op.f("fk_provider_operations_allocation_id_inventory_allocations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_operations")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_provider_operations_idempotency_key")),
    )
    op.create_index(
        "ix_provider_operations_retry_queue",
        "provider_operations",
        ["status", "next_attempt_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_provider_operations_retry_queue", table_name="provider_operations")
    op.drop_table("provider_operations")
    op.drop_table("order_items")
    op.drop_table("inventory_allocations")
    op.drop_table("reservation_items")
    op.drop_table("provider_credentials")
    op.drop_table("orders")
    op.drop_index("ix_inventory_levels_product_priority", table_name="inventory_levels")
    op.drop_table("inventory_levels")
    op.drop_index("ix_reservations_user_created", table_name="reservations")
    op.drop_index("ix_reservations_expiry_worker", table_name="reservations")
    op.drop_table("reservations")
    op.drop_table("products")
    op.drop_table("inventory_providers")
    # ### end Alembic commands ###
